---
Name: app-basics
After:
  - elemental
  - elemental-list
  - elementalvirtual
  - elemental-basics
  - a2nt-cms-niceties-options-elements
  - a2nt-cms-niceties-base-config
  - webapp-base-extensions
  - webapp-locale-fluent
  - silvershop-config
---

SilverStripe\CMS\Model\SiteTree:
  allowed_elements: null

DNADesign\ElementalList\Model\ElementList:
  allowed_elements: null

DNADesign\ElementalUserForms\Model\ElementForm:
  block_default_userforms_css: true
  block_default_userforms_js: true

SilverLeague\IDEAnnotator\DataObjectAnnotator:
  enabled: true
