---
Name: webapp
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

SilverStripe\View\SSViewer:
  source_file_comments: true
  themes:
    - '$public'
    - '$default'

Page:
  default_container_class: 'container'

#SilverStripe\Admin\LeftAndMain:
#  extra_requirements_javascript:
#    - 'colymba/gridfield-bulk-editing-tools:client/dist/js/main.js'
#    - 'colymba/gridfield-bulk-editing-tools:client/lang/en.js'
#  extra_requirements_css:
#    - 'colymba/gridfield-bulk-editing-tools:client/dist/styles/main.css'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
  - 'app/client/dist/css/app_cms.css'

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'app/client/dist/css/app_editor.css'
