---
Name: webapp
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

Page:
  default_container_class: 'container'

#SilverStripe\Admin\LeftAndMain:
#  extra_requirements_javascript:
#    - 'colymba/gridfield-bulk-editing-tools:client/dist/js/main.js'
#    - 'colymba/gridfield-bulk-editing-tools:client/lang/en.js'
#  extra_requirements_css:
#    - 'colymba/gridfield-bulk-editing-tools:client/dist/styles/main.css'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_js:
    - 'app/client/dist/css/app_cms.js'
  extra_requirements_css:
    - 'app/client/dist/css/app_cms.css'

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'app/client/dist/css/app_editor.css'

# Secure cookies
SilverStripe\Control\Session:
  cookie_secure: true
  strict_user_agent_check: false
