Site\Templates\DeferedRequirements:
  nojquery: false
  nofontawesome: false
  version: false
  static_domain: false
  custom_requirements:
    SilverShop\Page\AccountPageController:
      - SilverShop.Page.CheckoutPageController.js
      - SilverShop.Page.CheckoutPageController.css

